### ISSUE TITLE
暗黑模式切换

### ISSUE THREAD

**Issue by ghost** [Mogeko/mogege#32]
想请教一下博主，mogege主题中的暗黑模式的切换按钮没有起作用，是哪里需要设置吗？

**Comment by mogeko** [comment]
这个功能不需要设置的。

你用的什么浏览器？版本如何？

这玩意只在 Firefox 和 Chrome 上测试过

**Comment by ghost** [comment]
> 这个功能不需要设置的。
> 
> 你用的什么浏览器？版本如何？
> 
> 这玩意只在 Firefox 和 Chrome 上测试过

我用Chrome和Firefox点击没反应啊，Edge也没有...

**Comment by mogeko** [comment]
> 
> 
> > 这个功能不需要设置的。
> > 你用的什么浏览器？版本如何？
> > 这玩意只在 Firefox 和 Chrome 上测试过
> 
> 我用Chrome和Firefox点击没反应啊，Edge也没有...

你访问[我的博客](https://mogeko.me/)试试，能否切换到黑暗模式？

**Comment by ghost** [comment]
> > > 这个功能不需要设置的。
> > > 你用的什么浏览器？版本如何？
> > > 这玩意只在 Firefox 和 Chrome 上测试过
> > 
> > 
> > 我用Chrome和Firefox点击没反应啊，Edge也没有...
> 
> 你访问[我的博客](https://mogeko.me/)试试，能否切换到黑暗模式？

不能😭我点击了没反应

**Comment by mogeko** [comment]
emmm...
是不能切换到黑暗模式还是不能切换到白天模式？
你系统开的是不是黑暗模式？
@Licolnlee

**Comment by ghost** [comment]
> > > 这个功能不需要设置的。
> > > 你用的什么浏览器？版本如何？
> > > 这玩意只在 Firefox 和 Chrome 上测试过
> > 
> > 
> > 我用Chrome和Firefox点击没反应啊，Edge也没有...
> 
> 你访问[我的博客](https://mogeko.me/)试试，能否切换到黑暗模式？

但是原作者leaveit的是正常的，我这不好使我想怀疑可能是浏览器插件问题，但是我把插件全关了也不好使

**Comment by ghost** [comment]
> emmm...
> 是不能切换到黑暗模式还是不能切换到白天模式？
> 你系统开的是不是黑暗模式？
> @Licolnlee

是的我开的暗黑模式的，我切换成白天模式就好了...

**Comment by mogeko** [comment]
> 
> 
> > emmm...
> > 是不能切换到黑暗模式还是不能切换到白天模式？
> > 你系统开的是不是黑暗模式？
> > @Licolnlee
> 
> 是的我开的暗黑模式的，我切换成白天模式就好了...

哦哦，我这里的逻辑是这样的：
- 系统开启黑暗模式，主题强制开启黑暗模式
- 系统开启白天模式，你可以自己选择黑暗模式还是白天模式

等以后系统级别的黑暗模式普及了会砍掉按钮，主题的样式跟随系统

**Comment by ghost** [comment]
> > > emmm...
> > > 是不能切换到黑暗模式还是不能切换到白天模式？
> > > 你系统开的是不是黑暗模式？
> > > @Licolnlee
> > 
> > 
> > 是的我开的暗黑模式的，我切换成白天模式就好了...
> 
> 哦哦，我这里的逻辑是这样的：
> 
> * 系统开启黑暗模式，主题强制开启黑暗模式
> * 系统开启白天模式，你可以自己选择黑暗模式还是白天模式
> 
> 等以后系统级别的黑暗模式普及了会砍掉按钮，主题的样式跟随系统

哦是这样啊，好的谢谢博主耐心解答。感谢您制作的这么精美的主题。
