### ISSUE TITLE
Markdown 不显示图例

### ISSUE THREAD

**Issue by snowztail** [Mogeko/mogege#45]
如图. 可以设置默认显示图例吗?

![2020-05-17_13-00](https://user-images.githubusercontent.com/30973137/82144273-a90fca00-983e-11ea-9c9c-d6aef80d8c01.png)

**Comment by mogeko** [comment]
像这样？@SnowzTail
![Screenshot_2020-05-17 TEST Mogeko`s Blog(1)](https://user-images.githubusercontent.com/26341224/82145323-40c6e580-984a-11ea-96df-03e3da4b72d6.png)

**Comment by snowztail** [comment]
> 像这样？@SnowzTail
> ![Screenshot_2020-05-17 TEST Mogeko`s Blog(1)](https://user-images.githubusercontent.com/26341224/82145323-40c6e580-984a-11ea-96df-03e3da4b72d6.png)

是的, 十分感谢~

**Comment by mogeko** [comment]
> 
> 
> > 像这样？@SnowzTail
> > ![Screenshot_2020-05-17 TEST Mogeko`s Blog(1)](https://user-images.githubusercontent.com/26341224/82145323-40c6e580-984a-11ea-96df-03e3da4b72d6.png)
> 
> 是的, 十分感谢~

你这个需求可以用 Hugo 内置的 figure Shortcode 实现
```
{{< figure src="..." title="..." >}}
```

我记得我是实现了类似的功能的 (通过一种非标准的 Markdown 语法)，但我刚刚试了一下好像有点 bug，我试着修复一下

**Comment by mogeko** [comment]
等这个 PR 合到 master 后，你重新 pull 一下 @SnowzTail

然后你需要这么用
```
![Alt](URL "Title")
```
例如
```
![test](https://mogeko.github.io/blog-images/r/test/webp_test1.webp "这里是对图片的描述" )
```

![Screenshot_2020-05-17 Markdown Syntax Guide Mogeko`s Blog](https://user-images.githubusercontent.com/26341224/82147735-16782680-9850-11ea-892c-cc8954da45f6.png)

**Comment by snowztail** [comment]
好了 感谢ww
