### ISSUE TITLE
半角标点自动转换

### ISSUE THREAD

**Issue by snowztail** [Mogeko/mogege#47]
![2020-05-18_20-43](https://user-images.githubusercontent.com/30973137/82254007-f88eec80-9949-11ea-8e60-8ff655cb5615.png)

如图 (请点原图), 文本的半角标点
- 前面是中文时, 自动转换成全角标点 (红色)
- 前面是英文时不处理 (绿色)
- 疑似 bug (黄色)

可以选择停用这个功能吗? (使用 leaveit 主题时默认不转换全 / 半角)

**Comment by mogeko** [comment]
试试在 `config.toml` 中添一行：
```
[Params]
  restyleTextSpacing = false
```
@SnowzTail

**Comment by snowztail** [comment]
> 试试在 `config.toml` 中添一行：
> 
> ```
> [Params]
>   restyleTextSpacing = false
> ```
> 
> @SnowzTail

并没有用..

**Comment by mogeko** [comment]
你先拉取 `dev` 分支， reset 到这个 commit 86b44ec，然后试试

我怕还有别的 bug @SnowzTail

**Comment by snowztail** [comment]
> 你先拉取 `dev` 分支， reset 到这个 commit [86b44ec](https://github.com/Mogeko/mogege/commit/86b44ecdd99c1929ee5e187b8992726007d5e887)，然后试试
> 
> 我怕还有别的 bug @SnowzTail

解决了! 感谢ww
