### ISSUE TITLE
页面右上角点击切换 light/dark mode 的按钮不起作用

### ISSUE THREAD

**Issue by mousepotato** [Mogeko/mogege#49]
页面右上角点击切换 light/dark mode 的按钮不起作用

**Comment by mousepotato** [comment]
在 手机上是工作的，PC 端好像不工作。

**Comment by mogeko** [comment]
系统是开的 Dark mode 吗？@mousepotato 

如果是，就是正常的 #32

**Comment by mousepotato** [comment]
> 系统是开的 Dark mode 吗？@mousepotato
> 
> 如果是，就是正常的 #32

是的。原来是读取系统配置的。明白了。多谢
