### ISSUE TITLE
原LeaveIt的社交按钮功能

### ISSUE THREAD

**Issue by imlison** [Mogeko/mogege#54]
你好，请问原 LeaveIt 的社交按钮（首页的微博、GitHub 链接）功能是移除了吗？在配置文件里配置`[params.social]`无法显示效果。谢谢~
ps：建议建立 list 清单来说明移除或者添加了哪些功能。

**Comment by mogeko** [comment]
> 
> 
> 你好，请问原 LeaveIt 的社交按钮（首页的微博、GitHub 链接）功能是移除了吗？在配置文件里配置`[params.social]`无法显示效果。谢谢~
> ps：建议建立 list 清单来说明移除或者添加了哪些功能。

是的，社交按钮暂时移除了

感谢你的反馈，我会建立一个表格说明或者添加了哪些功能的

**Comment by imlison** [comment]
后续有计划支持原社交按钮吗，我个人觉得这功能挺不错的。

**Comment by mogeko** [comment]
> 后续有计划支持原社交按钮吗，我个人觉得这功能挺不错的。

我会考虑的移植的

**Comment by imlison** [comment]
> > 后续有计划支持原社交按钮吗，我个人觉得这功能挺不错的。
> 
> 我会考虑的移植的

好的，尽量以开关形式提供吧，不需要的人就直接不开启就好了
