### ISSUE TITLE
请问暗黑模式是怎么修复的呢？

### ISSUE THREAD

**Issue by xiaohao890809** [Mogeko/mogege#56]
原 Leaveit 切换暗黑模式的时候，当切换为黑色主题时，访问每个页面都会闪现一会儿白色，再变成黑色背景，mogege已经修复了这块，作者是怎么优化这块的呢

**Comment by mogeko** [comment]
我和 LeaveIt 实现黑暗模式的 JS 代码逻辑一模一样。唯一的区别是 LeaveIt 使用了 jQuery，而我没有。我不确定存在你所说的优化。

**Comment by xiaohao890809** [comment]
就是leaveit切换到黑暗主题的时候，点击一下其他页面的时候，会闪一下白屏，你可以体验下，但是你的博客不会闪一下

发自我的iPhone

**Comment by xiaohao890809** [comment]
> 我和 LeaveIt 实现黑暗模式的 JS 代码逻辑一模一样。唯一的区别是 LeaveIt 使用了 jQuery，而我没有。我不确定存在你所说的优化。

就是leaveit切换到黑暗主题的时候，点击一下其他页面的时候，会闪一下白屏，你可以体验下，但是你的博客不会闪一下,
https://liuzhichao.com/posts/

**Comment by mogeko** [comment]
> > 我和 LeaveIt 实现黑暗模式的 JS 代码逻辑一模一样。唯一的区别是 LeaveIt 使用了 jQuery，而我没有。我不确定存在你所说的优化。
> 
> 就是leaveit切换到黑暗主题的时候，点击一下其他页面的时候，会闪一下白屏，你可以体验下，但是你的博客不会闪一下,
> https://liuzhichao.com/posts/

那就不清楚了。。。

**Comment by telami** [comment]
@xiaohao890809 可以看一下我的blog
https://www.telami.cn/

**Comment by xiaohao890809** [comment]
请问，关于我得页面怎么添加呢？

发自我的iPhone

**Comment by xiaohao890809** [comment]
> @xiaohao890809 可以看一下我的blog
> https://www.telami.cn/

请问您是怎么修复的呢？另外，请问下，关于我得页面怎么添加呢？

**Comment by telami** [comment]
@xiaohao890809 
![image.png](https://i.loli.net/2020/08/28/WvpVDIekcOxBoGq.png)

**Comment by simon-lu** [comment]
> > @xiaohao890809 可以看一下我的blog
> > https://www.telami.cn/
> 
> 请问您是怎么修复的呢？另外，请问下，关于我得页面怎么添加呢？

页面的添加：
1. 使用`hugo new about.md`命令会在content目录下生成about.md文件，编辑里面的内容就可以了
2. 在根目录下config.toml添加菜单路径
