### ISSUE TITLE
请问怎么在文章内自定义字体颜色呢？

### ISSUE THREAD

**Issue by xiaohao890809** [Mogeko/mogege#58]
`<font color=red>xxx</font>`，这样子好像无效的，因为html标签被禁止了，请问下博主有其他方式可以实现吗？

**Comment by mogeko** [comment]
> `<font color=red>xxx</font>`，这样子好像无效的，因为html标签被禁止了，请问下博主有其他方式可以实现吗？

在 config.toml 中添加

```
​[​markup​.​goldmark​.​renderer​]
unsafe = true
```

就可以了

**Comment by xiaohao890809** [comment]
谢谢！

发自我的iPhone
